[book]
title = "The VOS Book"
description = "A peer-to-peer operating system for collaborative, replicated applications"
authors = ["Virto"]
language = "en"
src = "docs"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/virto-network/vos"
additional-css = []
