FROM docker.io/library/rust:1-alpine AS builder

RUN apk add --no-cache musl-dev
WORKDIR /src

COPY . .
RUN cargo build --release --target x86_64-unknown-linux-musl

FROM scratch
COPY --from=builder /src/target/x86_64-unknown-linux-musl/release/vosx /vosx
ENTRYPOINT ["/vosx"]
