[manifest]
name = "examples"

[service]
name = "scheduler"
path = "agents/scheduler/target/riscv64em-javm/release/scheduler.elf"

[[actors]]
name = "greeter"
path = "actors/greeter/target/riscv64em-javm/release/greeter.elf"

[[actors]]
name = "counter"
path = "actors/counter/target/riscv64em-javm/release/counter.elf"

[[actors]]
name = "fizzbuzz"
path = "actors/fizzbuzz/target/riscv64em-javm/release/fizzbuzz.elf"

[[actors]]
name = "hasher"
path = "actors/hasher/target/riscv64em-javm/release/hasher.elf"

[[actors]]
name = "display"
path = "actors/display/target/riscv64em-javm/release/display.elf"

[[actors]]
name = "animation"
path = "actors/animation/target/riscv64em-javm/release/animation.elf"

[[actors]]
name = "math"
path = "actors/math/target/riscv64em-javm/release/math.elf"

[[actors]]
name = "pipeline"
path = "actors/pipeline/target/riscv64em-javm/release/pipeline.elf"
