[manifest]
name = "examples"

[service]
name = "vos-agent"
path = "../crates/vos-agent/target/riscv64em-javm/release/vos-agent.elf"

[[actors]]
name = "greeter"
path = "greeter/target/riscv64em-javm/release/greeter.elf"

[[actors]]
name = "counter"
path = "counter/target/riscv64em-javm/release/counter.elf"

[[actors]]
name = "fizzbuzz"
path = "fizzbuzz/target/riscv64em-javm/release/fizzbuzz.elf"

[[actors]]
name = "hasher"
path = "hasher/target/riscv64em-javm/release/hasher.elf"

[[actors]]
name = "animation"
path = "animation/target/riscv64em-javm/release/animation.elf"
