build:
    cd ../crates/vos-agent && cargo build --release
    cd greeter && cargo build --release
    cd counter && cargo build --release
    cd fizzbuzz && cargo build --release
    cd hasher && cargo build --release
    cd animation && cargo build --release

run: build
    cargo run --manifest-path ../crates/vos/Cargo.toml --bin vosx -- Kunekt.toml
