build:
    cd agents/scheduler && cargo build --release
    cd actors/greeter && cargo build --release
    cd actors/counter && cargo build --release
    cd actors/fizzbuzz && cargo build --release
    cd actors/hasher && cargo build --release
    cd actors/display && cargo build --release
    cd actors/animation && cargo build --release
    cd actors/math && cargo build --release
    cd actors/pipeline && cargo build --release
    cd actors/crdt-counter && cargo build --release

run: build
    cargo run --manifest-path ../Cargo.toml -p vosx -- start space.toml --no-persist

list: build
    cargo run --manifest-path ../Cargo.toml -p vosx -- list space.toml
