build:
    cd agents/scheduler && cargo build --release
    cd actors/greeter && cargo build --release
    cd actors/counter && cargo build --release
    cd actors/fizzbuzz && cargo build --release
    cd actors/hasher && cargo build --release
    cd actors/display && cargo build --release
    cd actors/animation && cargo build --release
    cd actors/math && cargo build --release
    cd actors/pipeline && cargo build --release

run: build
    cargo run --manifest-path ../crates/vos/Cargo.toml --bin vosx -- Agent.toml

list: build
    cargo run --manifest-path ../crates/vos/Cargo.toml --bin vosx -- --list Agent.toml
