[manifest]
name = "hello-kunekt"

[[actors]]
name = "greeter"
path = "target/riscv64em-javm/release/greeter.elf"

[[actors]]
name = "counter"
path = "target/riscv64em-javm/release/counter.elf"

[[actors]]
name = "fizzbuzz"
path = "target/riscv64em-javm/release/fizzbuzz.elf"
