//! Actor message metadata — static descriptors for introspection.
//!
//! Generated by `#[messages]`, these structs describe an actor's message
//! interface without running the actor. Useful for tooling, routing,
//! and protocol-level introspection.

/// Describes a single field in a message struct.
pub struct FieldMeta {
    pub name: &'static str,
    pub ty: &'static str,
}

/// Describes one message variant (one `#[msg]` method).
pub struct MessageMeta {
    pub name: &'static str,
    pub is_query: bool,
    pub fields: &'static [FieldMeta],
}

/// Describes the full message interface of an actor.
pub struct ActorMeta {
    pub actor_name: &'static str,
    pub messages: &'static [MessageMeta],
}
