//! Cooperative single-threaded executor for PVM actor programs.
//!
//! Each `.await` point becomes a yield to the host scheduler, letting
//! other actors run. The host resumes this actor on the next tick.

use core::future::Future;
use core::pin::Pin;
use core::task::{Context, Poll, RawWaker, RawWakerVTable, Waker};

fn noop_raw_waker() -> RawWaker {
    fn noop(_: *const ()) {}
    fn clone(p: *const ()) -> RawWaker {
        RawWaker::new(p, &VTABLE)
    }
    const VTABLE: RawWakerVTable = RawWakerVTable::new(clone, noop, noop, noop);
    RawWaker::new(core::ptr::null(), &VTABLE)
}

/// Drive a future to completion, yielding to the PVM host on each `Pending`.
///
/// Every `.await` that returns `Pending` triggers a PVM yield syscall,
/// giving other actors a chance to run. When the host resumes this actor,
/// polling continues.
pub fn block_on<F: Future>(mut fut: F) -> F::Output {
    let waker = unsafe { Waker::from_raw(noop_raw_waker()) };
    let mut cx = Context::from_waker(&waker);
    let mut fut = unsafe { Pin::new_unchecked(&mut fut) };
    loop {
        match fut.as_mut().poll(&mut cx) {
            Poll::Ready(val) => return val,
            Poll::Pending => yield_to_host(),
        }
    }
}

/// A future that yields once then completes.
///
/// Used after message handlers to turn each `.await` into a cooperative
/// yield point. First poll returns `Pending`, second returns `Ready`.
pub struct Yield {
    yielded: bool,
}

impl Yield {
    pub fn once() -> Self {
        Self { yielded: false }
    }
}

impl Future for Yield {
    type Output = ();

    fn poll(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<()> {
        let this = self.get_mut();
        if this.yielded {
            Poll::Ready(())
        } else {
            this.yielded = true;
            Poll::Pending
        }
    }
}

/// Yield to the PVM host via the Yield syscall.
#[cfg(target_arch = "riscv64")]
fn yield_to_host() {
    unsafe {
        core::arch::asm!(
            "ecall",
            in("t0") 31u64, // Syscall::Yield = 31
            lateout("a0") _,
            options(nostack),
        );
    }
}

#[cfg(not(target_arch = "riscv64"))]
fn yield_to_host() {
    // No-op on non-PVM targets (tests, host-side usage)
}

/// Recv buffer size for the standard actor message loop.
#[cfg(feature = "guest")]
const RECV_BUF_SIZE: usize = 4096;

/// Standard actor lifecycle: construct from first message, then dispatch loop.
///
/// This is the entry point generated by `#[messages]` for each actor.
/// The executor controls the lifecycle:
///
/// 1. Yield to signal readiness
/// 2. Receive first message (constructor args), build the actor
/// 3. Checkpoint initial state
/// 4. Enter message loop: yield → recv → dispatch → checkpoint
///
/// `init` deserializes the first message payload and constructs the actor.
/// `dispatch` deserializes subsequent messages and calls the handler via `block_on`.
#[cfg(feature = "guest")]
pub fn main_loop<A: crate::Actor>(
    init: impl FnOnce(&[u8]) -> A,
    dispatch: impl Fn(&[u8], &mut A, &mut crate::Context<A>),
) {
    let mut buf = [0u8; RECV_BUF_SIZE];
    let mut ctx = crate::Context::new(crate::ActorId(
        pvx_scape::io::self_id() as u16,
    ));

    // Wait for constructor message from the executor
    let mut actor = loop {
        pvx_scape::io::yield_now();
        let n = pvx_scape::io::recv(&mut buf);
        if n > pvx_abi::msg::Header::SIZE as i32 {
            let payload = &buf[pvx_abi::msg::Header::SIZE..n as usize];
            break init(payload);
        }
    };
    pvx_scape::io::checkpoint();

    // Message loop
    loop {
        pvx_scape::io::yield_now();
        let n = pvx_scape::io::recv(&mut buf);
        if n > pvx_abi::msg::Header::SIZE as i32 {
            let payload = &buf[pvx_abi::msg::Header::SIZE..n as usize];
            dispatch(payload, &mut actor, &mut ctx);
            pvx_scape::io::checkpoint();
        }
        if ctx.stop_requested() {
            break;
        }
    }
}
