//! Poseidon2-over-M31 PCS primitives (native-recursion Stage-0).
//!
//! The recursion verifier-AIR commits inner proofs under an **M31-algebraic**
//! hash so the Merkle-decommit paths are cheap to re-express as constraints,
//! and replays an M31-algebraic Fiat-Shamir transcript so no Blake2s appears on
//! the commit/transcript path. This module is the lib-level home of those
//! primitives — the width-16 permutation, the [`MerkleHasherLifted`]
//! commitment hash, and the [`Channel`] transcript — so `prove`/`verify`/
//! `program_id` (and the standalone verifier crate) can select them via the
//! [`crate::recursion_pcs`] aliases under `--features poseidon2-channel`.
//!
//! The proving-side de-risk (`tests/poseidon2_pcs_spike.rs`) established the
//! one orphan-legal marker a custom channel needs on `CpuBackend`; the cross-
//! chip logup keystone (`tests/cross_chip_logup.rs`) established the
//! SIMD-trace-gen → `to_cpu` → `CpuBackend`-commit transplant ([`for_commit`]).
//!
//! Round constants are generated by the canonical Grain LFSR (POSEIDON eprint
//! 2019/458 §4.1, reused by Poseidon2 eprint 2023/323) seeded with our exact
//! parameters — see [`EXTERNAL_ROUND_CONSTS`] and
//! `tests/poseidon2_round_constants.rs` (the constants-vector test that
//! re-derives and pins them).

use alloc::rc::Rc;
use alloc::vec::Vec;

use num_traits::{One, Zero};
use serde::{Deserialize, Serialize};
use stwo::core::channel::{Channel, MerkleChannel};
use stwo::core::fields::m31::BaseField;
use stwo::core::fields::qm31::SecureField;
use stwo::core::vcs::hash::Hash;
use stwo::core::vcs_lifted::merkle_hasher::MerkleHasherLifted;

use core::cell::RefCell;
use core::ops::{Add, AddAssign, Mul, Sub};

// ── Poseidon2-over-M31 parameters (width 16; eprint 2023/323 §5) ──────────

pub const N_STATE: usize = 16;
pub const N_PARTIAL_ROUNDS: usize = 14;
pub const N_HALF_FULL_ROUNDS: usize = 4;
pub const FULL_ROUNDS: usize = 2 * N_HALF_FULL_ROUNDS;
pub const RATE: usize = 8;

// Width-16 M31 Poseidon2 round constants, generated by the canonical Grain LFSR
// (POSEIDON eprint 2019/458 §4.1, reused by Poseidon2 eprint 2023/323) seeded
// with our exact parameters (field=GF(2^31-1), x^5 S-box, t=16, R_F=8, R_P=14).
// The full reference generator + the consumption order (R_F/2 beginning full
// rounds, R_P internal, R_F/2 ending full rounds) live in
// `tests/poseidon2_round_constants.rs`, which re-derives and asserts these exact
// arrays (the constants-vector test). DO NOT hand-edit — re-run the generator.
// Changing these changes every commitment (and so the `{C_0,C_1}` allowlist).
pub const EXTERNAL_ROUND_CONSTS: [[BaseField; N_STATE]; FULL_ROUNDS] = [
    [
        BaseField::from_u32_unchecked(1988864850),
        BaseField::from_u32_unchecked(1893772157),
        BaseField::from_u32_unchecked(1025928330),
        BaseField::from_u32_unchecked(1839472709),
        BaseField::from_u32_unchecked(1611656994),
        BaseField::from_u32_unchecked(1104858731),
        BaseField::from_u32_unchecked(1694088660),
        BaseField::from_u32_unchecked(1564660990),
        BaseField::from_u32_unchecked(1991332205),
        BaseField::from_u32_unchecked(1875486487),
        BaseField::from_u32_unchecked(1890340790),
        BaseField::from_u32_unchecked(1658614),
        BaseField::from_u32_unchecked(582370530),
        BaseField::from_u32_unchecked(528029397),
        BaseField::from_u32_unchecked(1196956642),
        BaseField::from_u32_unchecked(655401251),
    ],
    [
        BaseField::from_u32_unchecked(1652877415),
        BaseField::from_u32_unchecked(26032894),
        BaseField::from_u32_unchecked(1576640243),
        BaseField::from_u32_unchecked(1277052539),
        BaseField::from_u32_unchecked(1450142396),
        BaseField::from_u32_unchecked(697623591),
        BaseField::from_u32_unchecked(1401580866),
        BaseField::from_u32_unchecked(1568404175),
        BaseField::from_u32_unchecked(2145004971),
        BaseField::from_u32_unchecked(265835716),
        BaseField::from_u32_unchecked(1183985610),
        BaseField::from_u32_unchecked(1031234465),
        BaseField::from_u32_unchecked(436012490),
        BaseField::from_u32_unchecked(172735299),
        BaseField::from_u32_unchecked(352802897),
        BaseField::from_u32_unchecked(1032863094),
    ],
    [
        BaseField::from_u32_unchecked(757665783),
        BaseField::from_u32_unchecked(1082171296),
        BaseField::from_u32_unchecked(1507509996),
        BaseField::from_u32_unchecked(309929890),
        BaseField::from_u32_unchecked(1807683232),
        BaseField::from_u32_unchecked(43258895),
        BaseField::from_u32_unchecked(611592566),
        BaseField::from_u32_unchecked(1854193793),
        BaseField::from_u32_unchecked(575164234),
        BaseField::from_u32_unchecked(894217817),
        BaseField::from_u32_unchecked(72613857),
        BaseField::from_u32_unchecked(1061659596),
        BaseField::from_u32_unchecked(8921166),
        BaseField::from_u32_unchecked(1617355017),
        BaseField::from_u32_unchecked(998001536),
        BaseField::from_u32_unchecked(1800758877),
    ],
    [
        BaseField::from_u32_unchecked(1002748055),
        BaseField::from_u32_unchecked(1935405944),
        BaseField::from_u32_unchecked(1351462722),
        BaseField::from_u32_unchecked(411368491),
        BaseField::from_u32_unchecked(1913975372),
        BaseField::from_u32_unchecked(1956167178),
        BaseField::from_u32_unchecked(442558016),
        BaseField::from_u32_unchecked(855898408),
        BaseField::from_u32_unchecked(699687798),
        BaseField::from_u32_unchecked(1553382248),
        BaseField::from_u32_unchecked(1708169125),
        BaseField::from_u32_unchecked(490049183),
        BaseField::from_u32_unchecked(1251643415),
        BaseField::from_u32_unchecked(1193594742),
        BaseField::from_u32_unchecked(880473871),
        BaseField::from_u32_unchecked(511174042),
    ],
    [
        BaseField::from_u32_unchecked(1460209171),
        BaseField::from_u32_unchecked(530850056),
        BaseField::from_u32_unchecked(398192464),
        BaseField::from_u32_unchecked(536338716),
        BaseField::from_u32_unchecked(75179210),
        BaseField::from_u32_unchecked(1309934197),
        BaseField::from_u32_unchecked(1335920373),
        BaseField::from_u32_unchecked(127611036),
        BaseField::from_u32_unchecked(291093831),
        BaseField::from_u32_unchecked(1832379621),
        BaseField::from_u32_unchecked(123571662),
        BaseField::from_u32_unchecked(303176864),
        BaseField::from_u32_unchecked(2137685056),
        BaseField::from_u32_unchecked(1759609530),
        BaseField::from_u32_unchecked(1418928155),
        BaseField::from_u32_unchecked(71608334),
    ],
    [
        BaseField::from_u32_unchecked(6616262),
        BaseField::from_u32_unchecked(1684515814),
        BaseField::from_u32_unchecked(1721194338),
        BaseField::from_u32_unchecked(720801691),
        BaseField::from_u32_unchecked(878392254),
        BaseField::from_u32_unchecked(460379263),
        BaseField::from_u32_unchecked(87930647),
        BaseField::from_u32_unchecked(940673483),
        BaseField::from_u32_unchecked(1136203256),
        BaseField::from_u32_unchecked(551499412),
        BaseField::from_u32_unchecked(256220454),
        BaseField::from_u32_unchecked(2007034235),
        BaseField::from_u32_unchecked(796124985),
        BaseField::from_u32_unchecked(410436345),
        BaseField::from_u32_unchecked(1705042586),
        BaseField::from_u32_unchecked(1286336446),
    ],
    [
        BaseField::from_u32_unchecked(1522340456),
        BaseField::from_u32_unchecked(1295296352),
        BaseField::from_u32_unchecked(309794713),
        BaseField::from_u32_unchecked(1772145068),
        BaseField::from_u32_unchecked(956898901),
        BaseField::from_u32_unchecked(2137070800),
        BaseField::from_u32_unchecked(988829146),
        BaseField::from_u32_unchecked(2059451359),
        BaseField::from_u32_unchecked(1846491684),
        BaseField::from_u32_unchecked(1105442551),
        BaseField::from_u32_unchecked(1236497773),
        BaseField::from_u32_unchecked(1452000568),
        BaseField::from_u32_unchecked(549485016),
        BaseField::from_u32_unchecked(385992492),
        BaseField::from_u32_unchecked(1987107948),
        BaseField::from_u32_unchecked(1514377269),
    ],
    [
        BaseField::from_u32_unchecked(2090065934),
        BaseField::from_u32_unchecked(1444920141),
        BaseField::from_u32_unchecked(293113979),
        BaseField::from_u32_unchecked(41120774),
        BaseField::from_u32_unchecked(855319793),
        BaseField::from_u32_unchecked(1663284746),
        BaseField::from_u32_unchecked(1789994008),
        BaseField::from_u32_unchecked(1120509162),
        BaseField::from_u32_unchecked(358222743),
        BaseField::from_u32_unchecked(1406256810),
        BaseField::from_u32_unchecked(735183687),
        BaseField::from_u32_unchecked(664485235),
        BaseField::from_u32_unchecked(1331641456),
        BaseField::from_u32_unchecked(38121324),
        BaseField::from_u32_unchecked(595810771),
        BaseField::from_u32_unchecked(1234594393),
    ],
];
pub const INTERNAL_ROUND_CONSTS: [BaseField; N_PARTIAL_ROUNDS] = [
    BaseField::from_u32_unchecked(2139014335),
    BaseField::from_u32_unchecked(69309039),
    BaseField::from_u32_unchecked(1368974953),
    BaseField::from_u32_unchecked(886780232),
    BaseField::from_u32_unchecked(1130937085),
    BaseField::from_u32_unchecked(1718115455),
    BaseField::from_u32_unchecked(2027103386),
    BaseField::from_u32_unchecked(1612216449),
    BaseField::from_u32_unchecked(1994053242),
    BaseField::from_u32_unchecked(110146615),
    BaseField::from_u32_unchecked(514413329),
    BaseField::from_u32_unchecked(1088763546),
    BaseField::from_u32_unchecked(955319292),
    BaseField::from_u32_unchecked(488794657),
];

// ── Linear layers (generic over the host field / a constraint expr) ────────

pub fn apply_m4<F>(x: [F; 4]) -> [F; 4]
where
    F: Clone + AddAssign<F> + Add<F, Output = F> + Sub<F, Output = F> + Mul<BaseField, Output = F>,
{
    let t0 = x[0].clone() + x[1].clone();
    let t02 = t0.clone() + t0.clone();
    let t1 = x[2].clone() + x[3].clone();
    let t12 = t1.clone() + t1.clone();
    let t2 = x[1].clone() + x[1].clone() + t1.clone();
    let t3 = x[3].clone() + x[3].clone() + t0.clone();
    let t4 = t12.clone() + t12.clone() + t3.clone();
    let t5 = t02.clone() + t02.clone() + t2.clone();
    let t6 = t3.clone() + t5.clone();
    let t7 = t2.clone() + t4.clone();
    [t6, t5, t7, t4]
}

pub fn apply_external_round_matrix<F>(state: &mut [F; 16])
where
    F: Clone + AddAssign<F> + Add<F, Output = F> + Sub<F, Output = F> + Mul<BaseField, Output = F>,
{
    for i in 0..4 {
        [
            state[4 * i],
            state[4 * i + 1],
            state[4 * i + 2],
            state[4 * i + 3],
        ] = apply_m4([
            state[4 * i].clone(),
            state[4 * i + 1].clone(),
            state[4 * i + 2].clone(),
            state[4 * i + 3].clone(),
        ]);
    }
    for j in 0..4 {
        let s =
            state[j].clone() + state[j + 4].clone() + state[j + 8].clone() + state[j + 12].clone();
        for i in 0..4 {
            state[4 * i + j] += s.clone();
        }
    }
}

pub fn apply_internal_round_matrix<F>(state: &mut [F; 16])
where
    F: Clone + AddAssign<F> + Add<F, Output = F> + Sub<F, Output = F> + Mul<BaseField, Output = F>,
{
    let sum = state[1..]
        .iter()
        .cloned()
        .fold(state[0].clone(), |acc, s| acc + s);
    state.iter_mut().enumerate().for_each(|(i, s)| {
        *s = s.clone() * BaseField::from_u32_unchecked(1 << (i + 1)) + sum.clone();
    });
}

// ── Host permutation (used by the hasher + channel) ───────────────────────

fn pow5(x: BaseField) -> BaseField {
    let x2 = x * x;
    x2 * x2 * x
}

/// The Poseidon2-over-M31 permutation: 4 full → 14 partial → 4 full rounds.
pub fn permute(state: &mut [BaseField; N_STATE]) {
    for round in 0..N_HALF_FULL_ROUNDS {
        for i in 0..N_STATE {
            state[i] += EXTERNAL_ROUND_CONSTS[round][i];
        }
        apply_external_round_matrix(state);
        for s in state.iter_mut() {
            *s = pow5(*s);
        }
    }
    for round in 0..N_PARTIAL_ROUNDS {
        state[0] += INTERNAL_ROUND_CONSTS[round];
        apply_internal_round_matrix(state);
        state[0] = pow5(state[0]);
    }
    for round in 0..N_HALF_FULL_ROUNDS {
        for i in 0..N_STATE {
            state[i] += EXTERNAL_ROUND_CONSTS[round + N_HALF_FULL_ROUNDS][i];
        }
        apply_external_round_matrix(state);
        for s in state.iter_mut() {
            *s = pow5(*s);
        }
    }
}

/// 2-to-1 node compression (the `hash_children` core): `parent[8] =
/// first8(permute(left[8] ‖ right[8]))`.
pub fn hash_children_m31(left: &[BaseField; 8], right: &[BaseField; 8]) -> [BaseField; 8] {
    let mut state = [BaseField::zero(); N_STATE];
    state[..8].copy_from_slice(left);
    state[8..].copy_from_slice(right);
    permute(&mut state);
    let mut out = [BaseField::zero(); 8];
    out.copy_from_slice(&state[..8]);
    out
}

// ── M31-algebraic Merkle hasher (the de-risked PCS commitment) ────────────

#[derive(Clone, Copy, PartialEq, Eq, Default, Debug, Serialize, Deserialize)]
pub struct P2Hash(pub [BaseField; 8]);

impl core::fmt::Display for P2Hash {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "P2Hash({:?})", self.0.map(|m| m.0))
    }
}
impl Hash for P2Hash {}

impl P2Hash {
    /// The canonical 32-byte serialization: the 8 M31 limbs as little-endian
    /// `u32`s. Inverse of [`P2Hash::from`] for canonical limbs (`< p`), which is
    /// always the case for a real commitment. This is the 32-byte wire form the
    /// program-commitment allowlist bakes (mirrors `Blake2sHash`'s `[u8; 32]`).
    pub fn to_bytes(&self) -> [u8; 8 * 4] {
        let mut out = [0u8; 32];
        for (i, limb) in self.0.iter().enumerate() {
            out[i * 4..i * 4 + 4].copy_from_slice(&limb.0.to_le_bytes());
        }
        out
    }
}

/// Parse a 32-byte commitment (8 little-endian `u32` limbs, each reduced mod
/// `p`) back into a `P2Hash`. Mirrors `Blake2sHash: From<&[u8]>` so the
/// channel-agnostic `CommitmentHash::from(&[u8])` in the prover extension works
/// under the Poseidon2-M31 stack. Panics on a non-32-byte slice (callers guard).
impl From<&[u8]> for P2Hash {
    fn from(bytes: &[u8]) -> Self {
        assert_eq!(bytes.len(), 32, "P2Hash requires exactly 32 bytes");
        let mut limbs = [BaseField::zero(); 8];
        for (i, limb) in limbs.iter_mut().enumerate() {
            let w = u32::from_le_bytes(bytes[i * 4..i * 4 + 4].try_into().unwrap());
            *limb = BaseField::reduce(w as u64);
        }
        P2Hash(limbs)
    }
}

#[derive(Clone, Debug)]
pub struct P2MerkleHasher {
    state: [BaseField; N_STATE],
    buffer: Vec<BaseField>,
}
impl Default for P2MerkleHasher {
    fn default() -> Self {
        Self {
            state: [BaseField::zero(); N_STATE],
            buffer: Vec::new(),
        }
    }
}
impl MerkleHasherLifted for P2MerkleHasher {
    type Hash = P2Hash;
    fn hash_children((left, right): (P2Hash, P2Hash)) -> P2Hash {
        P2Hash(hash_children_m31(&left.0, &right.0))
    }
    fn update_leaf(&mut self, column_values: &[BaseField]) {
        self.buffer.extend_from_slice(column_values);
        while self.buffer.len() >= RATE {
            for i in 0..RATE {
                self.state[i] += self.buffer[i];
            }
            permute(&mut self.state);
            self.buffer.drain(0..RATE);
        }
    }
    fn finalize(mut self) -> P2Hash {
        self.buffer.push(BaseField::one());
        while self.buffer.len() % RATE != 0 {
            self.buffer.push(BaseField::zero());
        }
        let mut i = 0;
        while i < self.buffer.len() {
            for j in 0..RATE {
                self.state[j] += self.buffer[i + j];
            }
            permute(&mut self.state);
            i += RATE;
        }
        let mut out = [BaseField::zero(); 8];
        out.copy_from_slice(&self.state[..8]);
        P2Hash(out)
    }
}

// Dummy serde for the hasher: `StarkProof<H>`'s derive bounds `H: Serialize +
// Deserialize`, but the hasher *value* is never serialized — only `H::Hash`
// (the committed roots) is. Mirrors stwo's own `Blake2sMerkleHasher` dummy
// impls so a `StarkProof<P2MerkleHasher>` (and thus `Proof`) is (de)serializable.
impl Serialize for P2MerkleHasher {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        let ser = serializer.serialize_struct("P2MerkleHasher", 0)?;
        serde::ser::SerializeStruct::end(ser)
    }
}
impl<'de> Deserialize<'de> for P2MerkleHasher {
    fn deserialize<D>(_deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        Ok(Self::default())
    }
}

// ── Poseidon2-M31 Fiat-Shamir channel (no Blake2s on commit OR transcript) ─

/// Which channel op produced a recorded permutation — pins the per-row op type
/// the native-recursion verifier-AIR's in-AIR transcript replay reconstructs.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PermKind {
    /// A sponge absorption step (one RATE chunk mixed in, digest advanced).
    Absorb,
    /// A squeeze step (digest + `n_draws` + `DRAW_DOMAIN` → fresh challenge).
    Squeeze,
    /// One of `verify_pow_nonce`'s two permutations (does NOT advance digest).
    Pow,
}

/// One width-16 permutation as the transcript drove it: its full input + output
/// state and which op invoked it. The ground truth the channel-replay AIR must
/// reproduce row-for-row.
///
/// `first_chunk` is `false` only for the continuation chunks of a multi-chunk
/// `absorb` (where the rate half carries the previous chunk's permuted state);
/// it is `true` for a fresh absorb's first chunk, every squeeze, and both pow
/// permutations.
#[derive(Clone, Copy, Debug)]
pub struct PermRecord {
    pub kind: PermKind,
    pub input: [BaseField; N_STATE],
    pub output: [BaseField; N_STATE],
    pub first_chunk: bool,
}

/// A sponge transcript over the width-16 Poseidon2-M31 permutation, mirroring
/// `Poseidon252Channel`: an 8-M31 `digest` + an `n_draws` counter for squeeze
/// freshness. Deterministic, so prover and verifier agree by construction.
///
/// When a `recorder` is attached (via [`Poseidon2M31Channel::recording`]) every
/// permutation the transcript performs is appended to it, in caller order — this
/// is how the native-recursion verifier-AIR pins the exact op sequence the stwo
/// verifier drives over a real segment proof. Default (no recorder) is
/// zero-overhead, so the production transcript is unaffected.
#[derive(Clone, Debug, Default)]
pub struct Poseidon2M31Channel {
    digest: [BaseField; 8],
    n_draws: u32,
    recorder: Option<Rc<RefCell<Vec<PermRecord>>>>,
}

const DRAW_DOMAIN: u32 = 3;

impl Poseidon2M31Channel {
    /// A fresh channel that records every permutation it performs into the
    /// shared buffer. Clones share the buffer, so a channel handed to a stwo
    /// `verify()` records the whole verifier transcript (the recursion seam
    /// [`crate::record_canonical_transcript`] uses this).
    pub fn recording(recorder: Rc<RefCell<Vec<PermRecord>>>) -> Self {
        Self {
            digest: [BaseField::zero(); 8],
            n_draws: 0,
            recorder: Some(recorder),
        }
    }

    /// Permute `state` in place, recording `(kind, input, output, first_chunk)`
    /// when a recorder is attached. Takes `&self` so `verify_pow_nonce` records
    /// too. Behaviorally identical to a bare `permute` when no recorder is set.
    fn rec_permute(&self, kind: PermKind, first_chunk: bool, state: &mut [BaseField; N_STATE]) {
        let input = *state;
        permute(state);
        if let Some(rec) = &self.recorder {
            rec.borrow_mut().push(PermRecord {
                kind,
                input,
                output: *state,
                first_chunk,
            });
        }
    }

    fn update_digest(&mut self, new_digest: [BaseField; 8]) {
        self.digest = new_digest;
        self.n_draws = 0;
    }

    fn absorb(&mut self, values: &[BaseField]) {
        let mut state = [BaseField::zero(); N_STATE];
        state[..8].copy_from_slice(&self.digest);
        if values.is_empty() {
            self.rec_permute(PermKind::Absorb, true, &mut state);
        } else {
            for (ci, chunk) in values.chunks(RATE).enumerate() {
                for (i, v) in chunk.iter().enumerate() {
                    state[8 + i] += *v;
                }
                self.rec_permute(PermKind::Absorb, ci == 0, &mut state);
            }
        }
        let mut d = [BaseField::zero(); 8];
        d.copy_from_slice(&state[..8]);
        self.update_digest(d);
    }

    fn squeeze8(&mut self) -> [BaseField; 8] {
        let mut state = [BaseField::zero(); N_STATE];
        state[..8].copy_from_slice(&self.digest);
        state[8] = BaseField::reduce(self.n_draws as u64);
        state[9] = BaseField::reduce(DRAW_DOMAIN as u64);
        self.rec_permute(PermKind::Squeeze, true, &mut state);
        self.n_draws += 1;
        let mut out = [BaseField::zero(); 8];
        out.copy_from_slice(&state[..8]);
        out
    }

    fn mix_root(&mut self, root: P2Hash) {
        self.absorb(&root.0);
    }
}

impl Channel for Poseidon2M31Channel {
    const BYTES_PER_HASH: usize = 32;

    fn verify_pow_nonce(&self, n_bits: u32, nonce: u64) -> bool {
        let mut s = [BaseField::zero(); N_STATE];
        s[..8].copy_from_slice(&self.digest);
        s[8] = BaseField::reduce(n_bits as u64);
        self.rec_permute(PermKind::Pow, true, &mut s);
        let mut s2 = [BaseField::zero(); N_STATE];
        s2[..8].copy_from_slice(&s[..8]);
        s2[8] = BaseField::reduce(nonce & 0xFFFF_FFFF);
        s2[9] = BaseField::reduce(nonce >> 32);
        self.rec_permute(PermKind::Pow, true, &mut s2);
        s2[0].0.trailing_zeros() >= n_bits
    }

    fn mix_u32s(&mut self, data: &[u32]) {
        let m: Vec<BaseField> = data.iter().map(|&x| BaseField::reduce(x as u64)).collect();
        self.absorb(&m);
    }

    fn mix_felts(&mut self, felts: &[SecureField]) {
        let m: Vec<BaseField> = felts.iter().flat_map(|x| x.to_m31_array()).collect();
        self.absorb(&m);
    }

    fn mix_u64(&mut self, value: u64) {
        self.absorb(&[
            BaseField::reduce(value & 0xFFFF_FFFF),
            BaseField::reduce(value >> 32),
        ]);
    }

    fn draw_secure_felt(&mut self) -> SecureField {
        let f = self.squeeze8();
        SecureField::from_m31_array([f[0], f[1], f[2], f[3]])
    }

    fn draw_secure_felts(&mut self, n_felts: usize) -> Vec<SecureField> {
        let mut out = Vec::with_capacity(n_felts);
        while out.len() < n_felts {
            let f = self.squeeze8();
            out.push(SecureField::from_m31_array([f[0], f[1], f[2], f[3]]));
            if out.len() < n_felts {
                out.push(SecureField::from_m31_array([f[4], f[5], f[6], f[7]]));
            }
        }
        out
    }

    fn draw_u32s(&mut self) -> Vec<u32> {
        self.squeeze8().iter().map(|m| m.0).collect()
    }
}

/// The Merkle channel pairing the Poseidon2-M31 hasher with the Poseidon2-M31
/// transcript — the full algebraic stack (no Blake2s anywhere on commit OR
/// Fiat-Shamir). Contrast the PCS spike's `P2MerkleChannel`, whose `C` is still
/// `Blake2sM31Channel` (it only swapped the commitment hash).
#[derive(Default)]
pub struct P2MerkleChannel;
impl MerkleChannel for P2MerkleChannel {
    type C = Poseidon2M31Channel;
    type H = P2MerkleHasher;
    fn mix_root(channel: &mut Self::C, root: <Self::H as MerkleHasherLifted>::Hash) {
        channel.mix_root(root);
    }
}

/// The one orphan-legal marker the custom channel needs: every super-bound of
/// `BackendForChannel<P2MerkleChannel>` is blanket-satisfied on `CpuBackend`;
/// legal because the trait's type parameter (`P2MerkleChannel`) is local.
#[cfg(feature = "prover")]
impl stwo::prover::backend::BackendForChannel<P2MerkleChannel>
    for stwo::prover::backend::CpuBackend
{
}
