//! Cooperative single-threaded executor for VOS actor programs.

use core::future::Future;
use core::pin::Pin;
use core::task::{Context, Poll, RawWaker, RawWakerVTable, Waker};

fn noop_raw_waker() -> RawWaker {
    fn noop(_: *const ()) {}
    fn clone(p: *const ()) -> RawWaker {
        RawWaker::new(p, &VTABLE)
    }
    const VTABLE: RawWakerVTable = RawWakerVTable::new(clone, noop, noop, noop);
    RawWaker::new(core::ptr::null(), &VTABLE)
}

/// Result of a single poll: either the future completed or it yielded.
pub enum RunResult<T> {
    Complete(T),
    Yielded,
}

/// Poll a future exactly once. Returns `Complete(val)` if ready, `Yielded` if pending.
pub fn try_poll<F: Future>(mut fut: F) -> RunResult<F::Output> {
    let waker = unsafe { Waker::from_raw(noop_raw_waker()) };
    let mut cx = Context::from_waker(&waker);
    let mut fut = unsafe { Pin::new_unchecked(&mut fut) };
    match fut.as_mut().poll(&mut cx) {
        Poll::Ready(val) => RunResult::Complete(val),
        Poll::Pending => RunResult::Yielded,
    }
}

/// A future that yields once then completes.
pub struct Yield {
    yielded: bool,
}

impl Yield {
    pub fn once() -> Self {
        Self { yielded: false }
    }
}

impl Future for Yield {
    type Output = ();

    fn poll(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<()> {
        let this = self.get_mut();
        if this.yielded {
            Poll::Ready(())
        } else {
            this.yielded = true;
            Poll::Pending
        }
    }
}

/// Halt the PVM by jumping to the halt sentinel address (2^32 - 2^16 = 0xFFFF0000).
///
/// On RV64, `lui` sign-extends so we can't directly load 0xFFFF0000.
/// Instead: load 0xFFFF via lui+addi, shift left 16, then djump.
#[cfg(target_arch = "riscv64")]
fn halt() -> ! {
    unsafe {
        core::arch::asm!(
            "lui t1, 0x10",       // t1 = 0x10000
            "addi t1, t1, -1",    // t1 = 0xFFFF
            "slli t1, t1, 16",    // t1 = 0xFFFF0000
            "jalr x0, t1, 0",    // djump → halt
            options(noreturn),
        );
    }
}

#[cfg(all(feature = "guest", not(target_arch = "riscv64")))]
fn halt() -> ! {
    panic!("halt is only supported on RISC-V targets");
}

/// Buffer size for hostcall data exchange.
#[cfg(feature = "guest")]
const BUF_SIZE: usize = 4096;

/// Storage key for persisted actor state.
#[cfg(feature = "guest")]
const STATE_KEY: &[u8] = b"__vos_actor_state";

/// Storage key for cooperative call results cache.
#[cfg(feature = "guest")]
const CALL_RESULTS_KEY: &[u8] = b"__vos_call_results";

/// Storage key for sleep-until tick count.
#[cfg(feature = "guest")]
const SLEEP_UNTIL_KEY: &[u8] = b"__vos_sleep_until";

/// Standard actor lifecycle — JAR-aligned fresh-PVM model.
///
/// Each invocation:
/// 1. Try loading existing state from storage via `read(STATE_KEY)`
/// 2. If no state, construct fresh actor (from init payload if needed)
/// 3. Load cooperative state (call_results) from storage
/// 4. Process all pending items (transfers delivered via `fetch()`)
/// 5. Flush effects after each handler
/// 6. If yield_now/sleep was called, self-schedule via transfer
/// 7. Persist state + cooperative metadata via `write()` and halt
///
/// The `init` closure receives `Option<&[u8]>`: `None` for parameterless
/// constructors (called immediately), `Some(bytes)` when init data is
/// fetched from the host. The `save` and `load` closures handle rkyv
/// serialization, generated by the `#[messages]` macro.
#[cfg(feature = "guest")]
pub fn main_loop<A: super::Actor>(
    needs_init_payload: bool,
    init: impl FnOnce(Option<&[u8]>) -> A,
    dispatch: impl Fn(&[u8], &mut A, &mut super::Context<A>) -> RunResult<bool>,
    save: impl Fn(&A) -> alloc::vec::Vec<u8>,
    load: impl Fn(&[u8]) -> A,
) {
    use vos_abi::guest::hostcalls;
    use vos_abi::guest::ecall;
    use vos_abi::hostcall::accumulate;

    let self_id = hostcalls::info() as u32;

    // Load cooperative state (call_results) from storage
    let mut buf = [0u8; BUF_SIZE];
    let call_results = {
        let n = hostcalls::read(CALL_RESULTS_KEY, &mut buf);
        if n > 0 && n < BUF_SIZE as u64 {
            // Deserialize Vec<Vec<u8>> from rkyv
            let bytes = &buf[..n as usize];
            let archived = unsafe {
                rkyv::access_unchecked::<rkyv::Archived<alloc::vec::Vec<alloc::vec::Vec<u8>>>>(bytes)
            };
            rkyv::deserialize::<alloc::vec::Vec<alloc::vec::Vec<u8>>, rkyv::rancor::Error>(archived)
                .unwrap_or_default()
        } else {
            alloc::vec::Vec::new()
        }
    };

    let mut ctx = super::Context::with_call_results(
        super::context::ServiceId(self_id),
        call_results,
    );

    // Step 1: Try loading existing state from storage
    let state_read = hostcalls::read(STATE_KEY, &mut buf);
    let mut actor = if state_read > 0 && state_read < BUF_SIZE as u64 {
        load(&buf[..state_read as usize])
    } else if needs_init_payload {
        // Constructor needs arguments — wait for init payload via FETCH
        loop {
            ecall::ecall0(accumulate::YIELD);
            let n = ecall::ecall2(vos_abi::hostcall::FETCH, buf.as_mut_ptr() as u64, buf.len() as u64);
            if n > 0 && n < BUF_SIZE as u64 {
                break init(Some(&buf[..n as usize]));
            }
        }
    } else {
        // Parameterless constructor — construct immediately
        init(None)
    };

    // Step 2: Process all pending items
    loop {
        let n = ecall::ecall2(vos_abi::hostcall::FETCH, buf.as_mut_ptr() as u64, buf.len() as u64);
        if n == 0 || n >= BUF_SIZE as u64 {
            break; // No more items
        }
        // Copy payload so we can replay if ask() suspends
        let payload_len = n as usize;
        let mut payload_buf = [0u8; BUF_SIZE];
        payload_buf[..payload_len].copy_from_slice(&buf[..payload_len]);

        match dispatch(&payload_buf[..payload_len], &mut actor, &mut ctx) {
            RunResult::Yielded => { ctx.flush_effects(); break; }
            RunResult::Complete(stop) => { ctx.flush_effects(); if stop { break; } }
        }

        // Resolve pending asks: call invoke(), cache result, replay handler
        while let Some(pending) = ctx.take_pending_ask() {
            let mut invoke_buf = [0u8; BUF_SIZE];
            let result_len = hostcalls::invoke(
                &target_code_hash(pending.target.0),
                &pending.payload,
                0, // 0 = use default gas
                &mut invoke_buf,
            );
            let result = if result_len > 0 && result_len < BUF_SIZE as u64 {
                invoke_buf[..result_len as usize].to_vec()
            } else {
                alloc::vec::Vec::new()
            };
            ctx.push_call_result_and_reset(result);

            // Replay: re-dispatch the same message with cached results
            match dispatch(&payload_buf[..payload_len], &mut actor, &mut ctx) {
                RunResult::Yielded => { ctx.flush_effects(); break; }
                RunResult::Complete(stop) => { ctx.flush_effects(); if stop { break; } }
            }
        }
    }

    // Step 3: Persist state
    let state_bytes = save(&actor);
    hostcalls::write(STATE_KEY, &state_bytes);

    // Step 4: Persist cooperative state if needed
    if ctx.self_scheduled() || ctx.take_pending_ask().is_some() {
        // Save call results for replay on next invocation
        let call_results = ctx.call_results();
        if !call_results.is_empty() {
            let call_results_vec: alloc::vec::Vec<alloc::vec::Vec<u8>> = call_results.to_vec();
            let bytes = rkyv::to_bytes::<rkyv::rancor::Error>(&call_results_vec).unwrap();
            hostcalls::write(CALL_RESULTS_KEY, &bytes);
        }

        // Self-schedule: transfer to ourselves to ensure we get invoked again
        if ctx.self_scheduled() {
            let sleep_ticks = ctx.sleep_ticks();
            if sleep_ticks > 0 {
                // Persist sleep-until counter
                let bytes = sleep_ticks.to_le_bytes();
                hostcalls::write(SLEEP_UNTIL_KEY, &bytes);
            }
            // Queue a transfer to self (empty payload = continue marker)
            hostcalls::transfer(
                super::context::ServiceId(self_id),
                0, 0, &[],
            );
        }
    } else {
        // Clear cooperative state if we finished normally
        hostcalls::write(CALL_RESULTS_KEY, &[]);
    }

    // Explicit PVM halt: jump to the halt sentinel address (2^32 - 2^16).
    // Cannot rely on ra being preserved through the call chain.
    halt();
}

/// Derive a code hash from a service ID for invoke() lookup.
///
/// Convention: the first 4 bytes are the service ID in LE, rest zeroed.
/// The vosx runtime recognizes this pattern and looks up the service's blob
/// by ID instead of by hash.
#[cfg(feature = "guest")]
fn target_code_hash(service_id: u32) -> [u8; 32] {
    let mut hash = [0u8; 32];
    hash[..4].copy_from_slice(&service_id.to_le_bytes());
    hash
}
