//! Cooperative single-threaded executor for VOS actor programs.

use core::future::Future;
use core::pin::Pin;
use core::task::{Context, Poll, RawWaker, RawWakerVTable, Waker};

fn noop_raw_waker() -> RawWaker {
    fn noop(_: *const ()) {}
    fn clone(p: *const ()) -> RawWaker {
        RawWaker::new(p, &VTABLE)
    }
    const VTABLE: RawWakerVTable = RawWakerVTable::new(clone, noop, noop, noop);
    RawWaker::new(core::ptr::null(), &VTABLE)
}

/// Drive a future to completion, yielding to the PVM host on each `Pending`.
pub fn block_on<F: Future>(mut fut: F) -> F::Output {
    let waker = unsafe { Waker::from_raw(noop_raw_waker()) };
    let mut cx = Context::from_waker(&waker);
    let mut fut = unsafe { Pin::new_unchecked(&mut fut) };
    loop {
        match fut.as_mut().poll(&mut cx) {
            Poll::Ready(val) => return val,
            Poll::Pending => yield_to_host(),
        }
    }
}

/// A future that yields once then completes.
pub struct Yield {
    yielded: bool,
}

impl Yield {
    pub fn once() -> Self {
        Self { yielded: false }
    }
}

impl Future for Yield {
    type Output = ();

    fn poll(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<()> {
        let this = self.get_mut();
        if this.yielded {
            Poll::Ready(())
        } else {
            this.yielded = true;
            Poll::Pending
        }
    }
}

/// Yield to the PVM host via the Yield hostcall.
#[cfg(target_arch = "riscv64")]
fn yield_to_host() {
    unsafe {
        core::arch::asm!(
            "ecall",
            in("t0") vos_abi::hostcall::YIELD as u64,
            lateout("a0") _,
            options(nostack),
        );
    }
}

#[cfg(not(target_arch = "riscv64"))]
fn yield_to_host() {
    // No-op on non-PVM targets (tests, host-side usage)
}

/// Buffer size for hostcall data exchange.
#[cfg(feature = "guest")]
const BUF_SIZE: usize = 4096;

/// Storage key for persisted actor state.
#[cfg(feature = "guest")]
const STATE_KEY: &[u8] = b"__vos_actor_state";

/// Standard actor lifecycle — JAR-aligned fresh-PVM model.
///
/// Each invocation:
/// 1. Try loading existing state from storage via `read(STATE_KEY)`
/// 2. If no state, receive init payload and construct fresh actor
/// 3. Process all pending items (transfers delivered via `fetch()`)
/// 4. Flush effects after each handler
/// 5. Persist state via `write(STATE_KEY)` and halt
///
/// The `save` and `load` closures handle rkyv serialization. They are
/// generated by the `#[messages]` macro so users don't need to worry
/// about the serialization details.
#[cfg(feature = "guest")]
pub fn main_loop<A: super::Actor>(
    init: impl FnOnce(&[u8]) -> A,
    dispatch: impl Fn(&[u8], &mut A, &mut super::Context<A>) -> bool,
    save: impl Fn(&A) -> alloc::vec::Vec<u8>,
    load: impl Fn(&[u8]) -> A,
) {
    use vos_abi::guest::hostcalls;
    use vos_abi::guest::ecall;
    use vos_abi::hostcall;

    let self_id = hostcalls::info() as u32;
    let mut ctx = super::Context::new(super::context::ServiceId(self_id));

    let mut buf = [0u8; BUF_SIZE];

    // Step 1: Try loading existing state from storage
    let state_read = hostcalls::read(STATE_KEY, &mut buf);
    let mut actor = if state_read > 0 && state_read < BUF_SIZE as u64 {
        load(&buf[..state_read as usize])
    } else {
        // No existing state — wait for init payload
        loop {
            ecall::ecall0(hostcall::YIELD);
            let n = ecall::ecall2(hostcall::FETCH, buf.as_mut_ptr() as u64, buf.len() as u64);
            if n > 0 && n < BUF_SIZE as u64 {
                break init(&buf[..n as usize]);
            }
        }
    };

    // Step 2: Process all pending items
    loop {
        let n = ecall::ecall2(hostcall::FETCH, buf.as_mut_ptr() as u64, buf.len() as u64);
        if n == 0 || n >= BUF_SIZE as u64 {
            break; // No more items
        }
        let payload = &buf[..n as usize];
        let stop = dispatch(payload, &mut actor, &mut ctx);
        ctx.flush_effects();
        if stop { break; }
    }

    // Step 3: Persist state and halt
    let state_bytes = save(&actor);
    hostcalls::write(STATE_KEY, &state_bytes);
}
