//! Test-vector generator for [`vos::zk::compute_io_hash`].
//!
//! The io-hash is the public-input binding external verifiers check against a
//! proof's bound register window, so out-of-tree reimplementations (e.g. a
//! verify-only environment that cannot depend on the `vos` crate) need a way
//! to pin byte-equality against the canonical implementation. This example
//! emits vectors FROM THE REAL implementation — any drift (domain strings,
//! inner field-hash construction, blake2b parameters) fails loudly in the
//! consumer's differential test.
//!
//! Usage (from the vos workspace root):
//!
//! ```text
//! # the vector table (redirect to a file to check into a consumer's fixtures):
//! cargo run -p vos --example io_hash_vectors
//!
//! # one-off: the io-hash for explicit hex bytes (e.g. to compute the hash a
//! # binding-fixture guest loads — see verifier-wasm-bench's `binding` mode):
//! cargo run -p vos --example io_hash_vectors -- <public_hex> [return_hex]
//! ```
//!
//! Output format (stdout, one vector per line, `#` comments allowed):
//! `public_hex<TAB>return_hex<TAB>io_hash_hex` — empty byte strings are
//! printed as `-` so the line always has three columns.

use vos::zk::compute_io_hash;

fn hex(bytes: &[u8]) -> String {
    if bytes.is_empty() {
        return "-".into();
    }
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn from_hex(s: &str) -> Vec<u8> {
    let s = s.strip_prefix("0x").unwrap_or(s);
    if s == "-" || s.is_empty() {
        return Vec::new();
    }
    assert!(s.len() % 2 == 0, "hex must have even length");
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("valid hex"))
        .collect()
}

fn emit(public: &[u8], ret: &[u8]) {
    let h = compute_io_hash(public, ret);
    println!("{}\t{}\t{}", hex(public), hex(ret), hex(&h));
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if !args.is_empty() {
        let public = from_hex(&args[0]);
        let ret = args.get(1).map(|s| from_hex(s)).unwrap_or_default();
        let h = compute_io_hash(&public, &ret);
        println!("io_hash={}", hex(&h));
        return;
    }

    println!("# vos::zk::compute_io_hash differential vectors");
    println!("# generated by: cargo run -p vos --example io_hash_vectors");
    println!("# columns: public_hex<TAB>return_hex<TAB>io_hash_hex ('-' = empty)");

    // The well-defined "no asserted public / return" value.
    emit(&[], &[]);
    // One side empty (both orders — the inner field hashes must not commute).
    emit(b"A", &[]);
    emit(&[], b"A");
    // The injectivity pair the field-hash construction exists for: raw
    // concatenation would collide these; fixed-width inner digests must not.
    emit(b"AB", b"C");
    emit(b"A", b"BC");
    // Multi-block blake2b (crosses the 128-byte compression boundary).
    emit(&[0xa5u8; 200], &[0x5au8; 77]);
    // A settlement-shaped binding: public = (id: u32, prev: [u8;32],
    // new: [u8;32], nonce: u64, aux_hash: [u8;32]) = 108 bytes, return = [].
    // Values here are ARBITRARY placeholders (real deployments pin their own);
    // this row pins the exact (108, 0) length class a settlement submits.
    let mut public = Vec::with_capacity(108);
    public.extend_from_slice(&1u32.to_le_bytes());
    public.extend_from_slice(&[0x11u8; 32]);
    public.extend_from_slice(&[0x22u8; 32]);
    public.extend_from_slice(&0u64.to_le_bytes());
    public.extend_from_slice(&[0x33u8; 32]);
    emit(&public, &[]);
}
